app_settings:
  app_type: "browser_use" # only lowercase letters, numbers, and underscores are allowed, e.g. salesforce, sap, zoho_crm, etc.
  app_name: "Browser Use" # this is the name of the app, should be a human-readable string.
  app_icon_svg_url: "https://asset.brandfetch.io/id9Bpy_H9O/iduCb9yKCI.png?c=1dxbfHSJFAPEGdCLU4o5B" # this is the icon of the app, should be a URL pointing to a SVG file.
  app_description: "AI browser automation for scripting, data extraction, and workflow automation."
  routes_directory: "src/modules" # this is the directory where the modules are located.

local_development_settings:
  sentry_dsn: ""
  cors_origins: ["*"]
  routes_directory: "src/modules"
  debug: true
  host: "0.0.0.0"
  port: 2003

